### PR TITLE
Allow discovery on all interfaces

### PR DESCRIPTION
**Pull request by sensiblepuffin**
Automatically finds IP and iterates through all your interfaces, which makes it easier to use VMs on virtual networks.

### CODE REVIEW

**Comment by TheAssassin** [comment]
@TobiGr who's the maintainer of this repository?

**Comment by TobiGr** [comment]
@TheAssassin Well, @wb9688 was the maintainer at the beginning. Now without further contributions, I'd suggest to give @Stypox some rights as he wanted to revive this project.

@sensiblepuffin Thanks for your contribution! I'll try to look at this PR at the end of this month, however, there are many things to do.

**Comment by wb9688** [comment]
Hmm… GitHub didn't send me an e-mail notification for this PR somehow. I'll
take a look at this patch before Monday.

@TheAssassin: I don't think I still have rights for this repo, since I
removed my GitHub account at some point. Could you please add me again (to
just this repo)?

**Comment by TheAssassin** [comment]
@wb9688 I added you as a collaborator.

**Comment by wb9688** [comment]
@sensiblepuffin: I pushed a new commit with support for actually playing videos, but now your PR has conflicts, could you please resolve them? I think the PR looks OK, but I'll only need to test it.

Edit: could I ask what your test setup is? Thanks a lot anyway!

**Comment by sensiblepuffin** [comment]
@wb9688: Believe it should be resolved now, I just tested playing a video. Good work, btw :)

I'm running GMediaRender Resurrect on a VM, hence why this was the first thing I'd written. I'm not really familiar with UPnP, so I had just been messing around with trying to get audio playing up until the other day.

**Comment by wb9688** [comment]
@sensiblepuffin: I just realized this wouldn't be the best way to handle it, since it'd take longer for every network interface you have. If I have e.g. 5 network interfaces, discovery would take 5 * 5 = 25 seconds this way, which is too long IMHO. It should be done on all interfaces in parallel.

**Comment by sensiblepuffin** [comment]
@wb9688: Yeah, I really should have done that before bringing it up before, sorry. It was really just supposed to be a workaround to let me test on my machine. c9655a8 spawns a thread for each address so that we only wait for a total of 5 seconds for discovery.

**Comment by wb9688** [comment]
@sensiblepuffin: The only problem now is that you aren't closing the sockets. Example to fix that:
```
        List<DatagramSocket> sockets = new ArrayList<DatagramSocket>();

        for (String addr : addresses) {
            DatagramSocket socket = new DatagramSocket(null);
            InetSocketAddress address = new InetSocketAddress(addr, 0);
            socket.bind(address);

            sockets.add(socket);
            tasks.add(new ReceiveDevices(socket));
        }

        executor.invokeAll(tasks, 5, TimeUnit.SECONDS);
        executor.shutdown();

        for (DatagramSocket socket : sockets) {
            socket.close();
        }
```
And then letting the `ReceiveDevices` class take `DatagramSocket`s instead of `String`s.

Also, you removed my fixes from a3fdfe27c93570bb688d7eec1810dac6416e6274 and 87995bc45c93c088152348c5ce54b5a79dd5d2b3. Just copy-paste the `request` variable from [here](https://github.com/TeamNewPipe/PipeCast/blob/master/src/main/java/org/schabi/newpipe/cast/protocols/upnp/UpnpDiscoverer.java) to fix that.

**Comment by sensiblepuffin** [comment]
@wb9688: Thanks for the suggestion on passing the sockets to the threads, it was a better solution.

This should have the /r and typo fix, not sure how I omitted them.

Thanks for being understanding, by the way, if you can't tell I'm very new at this. 😄

**Comment by wb9688** [comment]
I merged this, thanks!

**Pull request merged**
